### PR TITLE
fix(codegen) OpenAPI now works with `cargo-progenitor`

### PR DESCRIPTION
**Pull request by mkatychev**
# Pull Request

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
## Description

This PR addresses issues in `cargo-progenitor` code generation
by adding missing types to certain OpenAPI objects during code generation with the codegen below:
```
RUST_LOG="debug" cargo run -- -i ./openapi.yaml -o bnaclient -n bnaclient -v 1.0.0 --interface builder
```

## Checklist

- [] I have updated the documentation accordingly
- [] I have updated the Changelog (if applicable)

Fixes: : https://github.com/oxidecomputer/progenitor/issues/877#issuecomment-2427731013

### CODE REVIEW

**Comment by mkatychev** [comment]
I've run into a separate issue from https://github.com/oxidecomputer/progenitor/issues/877
with type.len assertions ehre:
https://github.com/oxidecomputer/progenitor/blob/1a61bf1e663af551f3cfe89116f08bbd88d6b57b/progenitor-impl/src/method.rs#L1264

This is run into with things like `getAnalysis` when there is more than one good and bad request:
https://github.com/PeopleForBikes/bna-api/blob/438bca09cc05e91bf138d83b9c17b099263b265d/openapi.yaml#L86-L101

**Comment by rgreinho** [comment]
We are almost there!

With these changes, the `openapi.yaml` is not valid anymore though:

image

We're very close, I'm sure we can make it both valid and work with `progenitor` 🤞

**Comment by rgreinho** [comment]
And yes! Just fixing these 3 violations makes the AOS file valid AND it still works with progenitor!

You can apply this patch to your branch and then we can merge 👍 

```patch
From 57349001d51730e8a457054ccb12cf29915fd411 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?R=C3=A9my=20Greinhofer?= <remy.greinhofer@gmail.com>
Date: Mon, 21 Oct 2024 20:53:01 -0500
Subject: [PATCH] Fix OAS violations

---
 openapi.yaml | 7 -------
 1 file changed, 7 deletions(-)

diff --git a/openapi.yaml b/openapi.yaml
index 4b0db10..3c30406 100644
--- a/openapi.yaml
+++ b/openapi.yaml
@@ -1043,9 +1043,6 @@ components:
       description: "A collection of errors"
       items:
         $ref: "#/components/schemas/error"
-      responses:
-        400:
-          $ref: "#/components/responses/bad_request"
     features:
       type: object
       properties:
@@ -1457,7 +1454,6 @@ components:
       description: "An analysis"
       content:
         application/json:
-          type: array
           schema:
             $ref: "#/components/schemas/analysis"
     bad_request:
@@ -1546,9 +1542,6 @@ components:
         application/json:
           schema:
             $ref: "#/components/schemas/enqueue"
-      responses:
-        403:
-          $ref: "#/components/responses/forbidden"
     forbidden:
       description: >
         You weren't authorized to make your request; most likely this indicates an issue
-- 
2.47.0


```

**Comment by mkatychev** [comment]
Thanks for the patch!

**Comment by rgreinho** [comment]
Thank you so much for fixing the generation! ❤️ 

I'll add the client as soon as we're done with the work on the API refactoring 💪

**Review by rgreinho — APPROVED** [review]
👍

**Pull request merged**
