### PR TITLE
Normalize the database

### PR DESCRIPTION
**Pull request by rgreinho**
Using the 1st normal form approach, this patch redesigns the initial
database schema.

Drive-bys:
- Uses DBML to document the database schema.
- Fixes the examples.
- Fixes the seeder.
- Fixes lambdas.

Signed-off-by: Rémy Greinhofer <remy.greinhofer@gmail.com>

### CODE REVIEW

**Comment by robahtou** [comment]
what's the 3rd Normal form here?

**Comment by rgreinho** [comment]
Isn't it the work we've done together last time?

**Comment by robahtou** [comment]
First normal form. Each table is a relation and we don't have repeating groups. And if a table satisfies a normal form it also satisfies all the preceding forms too. (a bit simplified but that's the mental model that I have in regards to this schema)

**Comment by rgreinho** [comment]
Copy that! I updated the description accordingly.

**Review by robahtou — APPROVED** [review]

**Pull request merged**
